export const bonusKeywords = [
  'créditos',
  'bônus',
  'bonus',
  'bônu',
  'crédito',
  'credito',
  'incentivo',
  'gratificação',
  'bonificação',
  'abono',
  'saldo extra',
  'premio extra',
  'brinde',
  'voucher',
  'vale',
  'saldo promocional',
  'dinheiro grátis',
  'créditos extras',
  'prêmio em dinheiro',
  'fichas grátis',
  'ganho extra',
  'extra points',
  'saldo bonificado',
]
