export const bonusKeywords = [
  'créditos',
  'bônus',
  'crédito',
  'bônu',
  'incentivo',
  'gratificação',
  'bonificação',
  'abono',
  'saldo extra',
  'promoção',
  'premiação',
  'premio extra',
  'recompensa',
  'ganhe',
  'oferta',
  'brinde',
  'voucher',
  'vale',
  'bônus de boas-vindas',
  'bônus de recarga',
  'bônus instantâneo',
  'bônus em dinheiro',
  'saldo promocional',
  'dinheiro grátis',
  'créditos extras',
  'prêmio em dinheiro',
  'bônus de entrada',
  'cash bonus',
  'fichas grátis',
  'ganho extra',
  'extra points',
  'money bonus',
  'bonus dinh€ir0',
  'bonus dinh3ir0',
  'bonus dinhe1r0',
  'bonus dinheir0',
  'saldo bonificado',
]
